# Generated by Django 3.0.5 on 2020-04-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID', models.CharField(max_length=50, unique=True, verbose_name='FID')),
                ('TID', models.CharField(max_length=50, unique=True, verbose_name='TID')),
                ('UID', models.CharField(max_length=50, unique=True, verbose_name='UID')),
            ],
            options={
                'verbose_name': 'UnionUser',
                'verbose_name_plural': 'UnionUser',
                'db_table': 'UnionUser1',
            },
        ),
    ]
