# Generated by Django 3.0.5 on 2020-04-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipUser',
            fields=[
                ('ID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpw', models.CharField(max_length=200, verbose_name='PSW')),
            ],
            options={
                'verbose_name': 'TipUser',
                'verbose_name_plural': 'TipUser',
                'db_table': 'TipUser1',
            },
        ),
        migrations.CreateModel(
            name='TipMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=50, verbose_name='TIPID')),
                ('date', models.CharField(max_length=50, verbose_name='Date')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'TipMessage',
                'verbose_name_plural': 'TipMessage',
                'db_table': 'TipMessage1',
                'unique_together': {('UID', 'date')},
            },
        ),
    ]
