# Generated by Django 3.0.5 on 2020-04-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipmessage',
            name='TID',
            field=models.CharField(default=123, max_length=50, verbose_name='TID'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tipmessage',
            unique_together={('TID', 'date')},
        ),
        migrations.RemoveField(
            model_name='tipmessage',
            name='UID',
        ),
    ]
